--
-- PostgreSQL database dump
--

-- Dumped from database version 10.5
-- Dumped by pg_dump version 11.1

-- Started on 2019-05-24 08:48:21

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 627 (class 1259 OID 210725)
-- Name: metadaten; Type: TABLE; Schema: radverkehr; Owner: postgres
--

CREATE TABLE radverkehr.metadaten (
    id integer NOT NULL,
    fuer character varying,
    richtung character varying,
    name character varying,
    comment character varying,
    source character varying,
    number character varying,
    type character varying,
    garmin_display_color character varying,
    description character varying,
    link_url character varying,
    link_text character varying,
    author_name character varying,
    author_link_text character varying,
    author_link_url character varying,
    copyright_year integer,
    copyright_license character varying,
    copyright_author character varying,
    creation_time character varying,
    keywords character varying
);


ALTER TABLE radverkehr.metadaten OWNER TO postgres;

--
-- TOC entry 626 (class 1259 OID 210723)
-- Name: metadaten_id_seq; Type: SEQUENCE; Schema: radverkehr; Owner: postgres
--

CREATE SEQUENCE radverkehr.metadaten_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE radverkehr.metadaten_id_seq OWNER TO postgres;

--
-- TOC entry 5610 (class 0 OID 0)
-- Dependencies: 626
-- Name: metadaten_id_seq; Type: SEQUENCE OWNED BY; Schema: radverkehr; Owner: postgres
--

ALTER SEQUENCE radverkehr.metadaten_id_seq OWNED BY radverkehr.metadaten.id;


--
-- TOC entry 5465 (class 2604 OID 210728)
-- Name: metadaten id; Type: DEFAULT; Schema: radverkehr; Owner: postgres
--

ALTER TABLE ONLY radverkehr.metadaten ALTER COLUMN id SET DEFAULT nextval('radverkehr.metadaten_id_seq'::regclass);


--
-- TOC entry 5604 (class 0 OID 210725)
-- Dependencies: 627
-- Data for Name: metadaten; Type: TABLE DATA; Schema: radverkehr; Owner: postgres
--

COPY radverkehr.metadaten (id, fuer, richtung, name, comment, source, number, type, garmin_display_color, description, link_url, link_text, author_name, author_link_text, author_link_url, copyright_year, copyright_license, copyright_author, creation_time, keywords) FROM stdin;
1	alle	\N	Velorouten Hamburg	\N	\N	\N	\N	\N	Das hamburgweite, 280 km lange Velorouten-Netz besteht aus sternförmig ins Zentrum führenden Routen (VR 1-12) und Ringrouten (VR 13-14). Sie dienen dem bezirksübergreifenden Alltags-Radverkehr auf mittleren und längeren Strecken und sind zügig, sicher und komfortabel zu befahren. Die Velorouten werden im Rahmen eines umfangreichen Ausbauprogramms derzeit für den Radverkehr optimiert, wovon die Hälfte abgeschlossen ist. Nach der weitgehenden Fertigstellung 2021 wird auch eine Beschilderung vorgenommen. Bis dahin sollen diese GPS-Tracks eine Navigationshilfe bei der Nutzung sein.	http://www.hamburg.de/radverkehr/300372/velorouten/	Velorouten im Internet	Freie und Hansestadt Hamburg, Behörde für Wirtschaft, Verkehr und Innovation	BWVI	http://www.hamburg.de/bwvi/	2019	Datenlizenz Deutschland Namensnennung 2.0	Freie und Hansestadt Hamburg, Behörde für Wirtschaft, Verkehr und Innovation	\N	\N
2	1	einwärts	\N	Die Veloroute 1 führt von Rissen über Sülldorf, Blankenese, Nienstedten, Othmrschen, Ottensen, Altona-Altstadt und St.Pauli in die Hamburger Innenstadt. Die 20,5 km verlaufen überwiegend durch Tempo 30 Wohnstraßen und an kurzen Teilstrecken auch an Hauptverkehrsstraßen. Dabei können z.B. folgende Ziele erreicht werden: S-Blankenese, Neuer Botanischer Garten (Loki-Schmidt-Garten) mit Fakultäten der Universität Hamburg, Asklepios Klinik Altona, UCI-Entertainment-Center Othmarschen, Bahnhof Altona, Heiligengeistfeld, Messehallen, Laeiszhalle.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	1	\N	\N	Rissen - Blankenese - Othmarschen - Altona - City	http://www.hamburg.de/radverkehr/418898/veloroute-1/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
3	1	auswärts	\N	Die Veloroute 1 führt vom Rathausmerkt in der Hamburger Innenstadt über St. Pauli, Altona-Altstadt, Ottensen, Othmarschen, Blankenese und Sülldorf nach Rissen. Die 20,5 km verlaufen überwiegend durch Tempo 30 Wohnstraßen und an kurzen Teilstrecken auch an Hauptverkehrsstraßen. Dabei können z.B. folgende Ziele erreicht werden: Laeiszhalle, Messehallen, Heiligengeistfeld, Bahnhof Altona, UCI-Entertainment-Center Othmarschen, Asklepios Klinik Altona, Neuer Botanischer Garten (Loki-Schmidt-Garten) mit Fakultäten der Universität Hamburg, S-Blankenese.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	1	\N	\N	City - Altona - Othmarschen - Blankenese - Rissen	http://www.hamburg.de/radverkehr/418898/veloroute-1/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
4	2	einwärts	\N	Die Veloroute 2 führt von Eidelstedt über Stellingen, Eimsbüttel, Sternschanze und St. Pauli zum Rathausmarkt in der Hamburger Innenstadt. Die 11 km verlaufen überwiegend auf Nebenstraßen durch Wohngebiete und durch Kleingärten in Stellingen. Dabei können z.B. folgende Ziele erreicht werden: Eidelstedt Center, Hagenbecks Tierpark, Heiligengeistfeld, Messehallen.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	2	\N	\N	Eidelstedt - Stellingen - Eimsbüttel - City	http://www.hamburg.de/radverkehr/418914/veloroute-2/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
5	2	auswärts	\N	Die Veloroute 2 führt vom Rathausmarkt in der Hamburger Innenstadt über St. Pauli, Sternschanze, Eimsbüttel, Stellingen nach Eidelstedt. Die 11 km verlaufen überweigend auf Nebenstraßen durch Wohngebiete und durch Kleingärten in Stellingen. Dabei können z.B. folgende Ziele erreicht werden: Eidelstedt Center, Hagenbecks Tierpark, Heiligengeistfeld, Messehallen.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	2	\N	\N	City - Eimsbüttel - Stellingen - Eidelstedt	http://www.hamburg.de/radverkehr/418914/veloroute-2/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
6	3	einwärts	\N	Die Veloroute 3 führt von Niendorf über Lokstedt, Eimsbüttel und Rotherbaum in die Hamburger Innenstadt zum Rathausmarkt. Die 13 km verlaufen überwiegend durch Tempo-30-Zonen. Ein kleines Teilstück führt entlang einer Hauptverkehrsstraße und in Lokstedt geht es durch eine Kleingartenkolonie. Dabei können z.B. folgende Ziele erreicht werden: Tibarg am Niendorfer Markt, Niendorfer Gehege, Grindelviertel, Universität Hamburg, Bahnhof Dammtor, CCH, Planten un Blomen, Gänsemarkt, Jungfernstieg.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	3	\N	\N	Niendorf - Rotherbaum/Uni - City	http://www.hamburg.de/radverkehr/418922/veloroute-3/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
7	3	auswärts	\N	Die Veloroute 3 führt vom Rathausmarkt in der Hamburger Innenstadt über Rotherbaum, Eimsbüttel und Lokstedt nach Niendorf. Die 13 km verlaufen überwiegend durch Tempo-30-Zonen, ein Teilstück führt entlang einer Hauptverkehsrstraße und es geht in Lokstedt durch eine Kleingartenkolonie. Auf der Fahrt können Sie z.B. folgende Ziele erreichen: Jungfernstieg, Gänsemarkt, Planten un Blomen, CCH, Bahnhof Dammtor, Universität Hamburg, Grindelviertel, Niendorfer Gehege, Tibarg am Niendorf Markt.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	3	\N	\N	City - Rotherbaum/Uni - Niendorf	http://www.hamburg.de/radverkehr/418922/veloroute-3/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
8	4	einwärts	\N	Die Veloroute 4 führt von Langenhorn über Fuhlsbüttel, Alsterdorf, Winterhude, Harvesterhude und Rotherbaum zum Rathausmarkt in der Hamburger Innenstadt. Die 18 km führen überwiegend durch ruhige Wohngebiete. Ab Alsterdorf führt die Route dann an der Alster entlang. Dabei können sie z.B. diese Ziele erreichen: Asklepios Klinik Nord, Flughafen, Sporthalle Hamburg, Winterhuder Marktplatz, westliches Alsterufer, Junfernstieg.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	4	\N	\N	Langenhorn - Fuhlsbüttel - Alsterdorf - Winterhude - Harvesterhude - City 	http://www.hamburg.de/radverkehr/418942/veloroute-4/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
9	4	auswärts	\N	Die Veloroute 4 führt vom Rathausmarkt in der Hamburger Innenstadt über Rotherbaum, Harvesterhude, Winterhude, Alsterdorf und Fuhlsbüttel bis nach Langenhorn. Die 18 km verlaufen überwiegend durch ruhige wohngebite. Ein großer Teil der Route verläuft parallel zur Alster. Dabei können sie z.B. folgende Ziele erreichen: Jungfernstieg, westliches Alsterufer, Winterhuder Marktplatz, Sporthalle Hamburg, Flughafen, Asklepios Klinik Nord.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	4	\N	\N	City - Harvestehude - Winterhude - Alsterdorf - Fuhlsbüttel - Langenhorn	http://www.hamburg.de/radverkehr/418942/veloroute-4/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
10	5	einwärts	\N	Die Veloroute 5 führt von Duvenstedt über Sasel, Poppenbüttel, Bramfeld, Steilshoop, Barmbek, Uhlenhorst und St. Georg zum Rathausmarkt in der Hamburger Innenstadt. Die 22,5 km verlaufen überwiegend durch Nebenstraßen, in Innenstadtnähe geht es dann auch entlang einiger Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: Alster-Einkaufs-Zentrum, Friedhof Ohlsdorf, Bramfelder Chaussee, Siedlung Steilshoop, Fuhlsbüttler Straße, U/S-Barmbek, U-Hamburger Straße, Behörden für Schule und Berufsbildung/Arbeit, Soziales, Familie und Integration,  östliches Alsterufer, Kunsthalle.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	5	\N	\N	Duvenstedt - Poppenbüttel - Bramfeld - Barmbek - Uhlenhorst - City	http://www.hamburg.de/radverkehr/426674/veloroute-5/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
11	5	auswärts	\N	Die Veloroute 5 führt vom Rathausmarkt in der Hamburger Innenstadt über St. Georg, Uhlenhorst, Barmbek, Steilshoop, Bramfeld, Poppenbüttel und Sasel nach Duvenstedt. Die 22,5 km verlaufen überwiegend über Nebenstraßen, nur am Anfang geht es über ein paar Hauptverkehrsstraßen. Dabei könne sie z.B. folgende Ziele erreichen: Kunsthalle, östliches Alsterufer, Behörden für Schule und Berufsbildung/Arbeit, Soziales, Familie und Integration, U-Hamburger Straße, U/S-Barmbek, Fuhlsbüttler Straße, Siedlung Steilshoop, Bramfelder Chaussee, Friedhof Ohlsdorf, Alster-Einkaufs-Zentrum.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	5	\N	\N	City - Uhlenhorst - Barmbek - Bramfeld - Poppenbüttel - Duvenstedt	http://www.hamburg.de/radverkehr/426674/veloroute-5/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
12	6	einwärts	\N	Die Veloroute 6 führt von  Volksdorf über Farmsen-Berne, Wandsbek, Dulsberg, Barmbek-Süd, Uhlenhorst und St. Georg zum Rathausmarkt in der Hamburger Innenstadt. Die 18 km verlaufen überwiegend durch Nebenstraßen und in Volksdorf durch einen kleinen Grünzug. Dabei könne sie z.B. folgende Ziele erreichen: U-Volksdorf, Ev. Krankenhaus, Berufliche Schule Farmsen, Einkaufstreffpunkt Farmsen, Bundeswehrkrankenhaus, U-Wandsbek-Gartstadt, Sportpark Dulsberg, Schön Klinik Hamburg Eilbek, Hochschule für bildende Künste HfbK/HAW/Hamburg Media School, Schule für Ernährung und Hauswirtschaft, östliches Alsterufer, Kunsthalle.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	6	\N	\N	Volksdorf - Farmsen-Berne - Dulsberg - Hohenfelde - City	http://www.hamburg.de/radverkehr/426692/veloroute-6/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
13	6	auswärts	\N	Die Veloroute 6 führt vom Rathausmarkt über St.Georg, Uhlenhorst, Barmbek-Süd, Dulsberg, Wandsbek und Farmsen-Berne nach Volksdorf. Die 18 km verlaufen überwiegend durch Nebenstraßen und in Volksdorf durch einen kleinen Grünzug. Dabei können sie z.B. folgende Ziele erreichen: Kunsthalle, östliches Alsterufer, Schule für Ernährung und Hauswirtschaft, Hochschule für bildende Künste HfbK/HAW/Hamburg Media School, Schön Klinik Hamburg Eilbek, Sportpark Dulsberg, U-Wandsbek-Gartenstadt, Bundeswehrkrankenhaus, Einkaufstreffpunkt Farmsen, Berufliche Schule Farmsen, Ev. Krankenhaus, U-Volksdorf.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	6	\N	\N	City - Hohenfelde - Dulsberg - Farmsen - Berne - Volksdorf	http://www.hamburg.de/radverkehr/426692/veloroute-6/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
14	7	einwärts	\N	Die Veloroute 7 führt von Rahlstedt über Jenfeld, Marienthal, Eilbek, Hohenfelde und St. Georg zum Rathausmarkt in der Hamburger Innenstadt. Die 14 km verlaufen über Nebenstraßen und über Hauptverkehrsstraßen. Dabei können sie z. B. folgende Ziele erreichen: Bahnhof Rahlstedt, Studio Hamburg, Asklepios Klinik Wandsbek, Bahnhof Wandsbek, U-Wandsbek Markt, Marienkrankenhaus, Gewerbeschulen Angerstraße, Hochschule für Angewandte Wissenschaften, Asklepios Klinik St. Georg, Museum für Kunst und Gewerbe, Hauptbahnhof, Mönckebergstraße.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	7	\N	\N	Rahlstedt - Jenfeld - Wandsbek-Markt - Eilbek - St. Georg - City	http://www.hamburg.de/radverkehr/426718/veloroute-7/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
15	7	auswärts	\N	Die Veloroute 7 führt vom Rathausmarkt in der Hamburger Innenstadt über St. Georg, Hohenfelde, Eilbek, Marienthal und Jenfeld nach Rahlstedt. Die 14 km verluafen durch Nebnstraßen, aber auch über Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: Mönckebergstraße, Hauptbahnhof, Museum für Kunst und Gewerbe, Asklepios Klinik St. Georg, Studio Hamburg, Bahnhof Rahlstedt. 	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	7	\N	\N	City - St. Georg - Eilbek - Wandsbek-Markt - Jenfeld - Rahlstedt	http://www.hamburg.de/radverkehr/426718/veloroute-7/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
16	8	einwärts	\N	Die Veloroute 8 führt von Bergedorf über Lohbrügge, Billstedt, Horn, Hamm, Borgfelde und St. Georg zum Rathausmarkt in der Hamburger Innenstadt. Die 18 km verlaufen durch Nebenstraßen und in Lohbrügge durch einen längeren Grünzug. Dabei können sie z.B. folgende Ziele erreichen: Bahnhof Bergedorf, BG Klinikum Hamburg/Unfallkrankenhaus Boberg, Naturschutzgebiet Boberger Niederung, Billstedter Hauptstraße, Horner Rennbahn, Berufs- und Gewerbeschulen Hammer Landstraße, U/S-Berliner Tor, Hochschule für Angewandte Wissenschaften, Agentur für Arbeit, Museum für Kunst und Gewerbe, Hauptbahnhof, Mönckebergstraße.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	8	\N	\N	Bergedorf - Billstedt - Hamm - Borgfelde - City	http://www.hamburg.de/radverkehr/426726/veloroute-8/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
17	8	auswärts	\N	Die Veloroute 8 führt vom Rathausmarkt über St. Georg, Borgfelde, Hamm, Horn, Billstedt und Lohbrügge nach Bergedorf. Die 18 km verlaufen auf Nebenstraßen und in Lohbrügge durch einen längeren Grünzug. Dabei können sie z.B. folgende Ziele erreichen: Mönckebergstraße, Hauptbahnhof, Museum für Kunst und Gewerbe, Agentur für Arbeit, Hochschule für Angewandte Wissenschaften, U/S-Berliner Tor, Berufs- und Gewerbeschulen Hammer Landstraße, Horner Rennbahn, Billstedter Hauptstraße, Naturschutzgebiet Boberger Niederung, BG Klinikum Hamburg/Unfallkrankenhaus Boberg, Bahnhof Bergedorf.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	8	\N	\N	City - Borgfelde - Hamm - Billstedt - Bergedorf	http://www.hamburg.de/radverkehr/426726/veloroute-8/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
18	9	einwärts	\N	Die Veloroute 9 führt von Bergedorf über Billwerder, Billbrook, Rothenburgsort und Hammerbrook zum Rathausmarkt in der Hamburger Innenstadt. Die 19 km verlaufen durch Industriegebite, Nebenstraßen und überwiegend durch einen Grünzug. Dabei können sie z.B. folgende Ziele erreichen: Bahnhof Bergedorf, Hauni Maschinenbau GmbH, S-Allermöhe, Industriegebiet Billbrook, Hamburg Wasser, Elbpark Entenwerder, Deichtorhallen, Zentralbibliothek, Hauptbahnhof, Mönckebergstraße.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	9	\N	\N	Bergedorf - Allermöhe - Moorfleet - Rothenburgsort - Hammerbrook - City	http://www.hamburg.de/radverkehr/426734/veloroute-9/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
19	9	auswärts	\N	Die Veloroute 9 führt vom Rathausmarkt über Hammerbrook, Rothenburgsort, Billbrook und Billwerder nach Bergedorf. Die 19 km verlaufen durch ein Industreigebiet, Nebenstraßen und überwiegend durch einen Grünzug. Dabei können sie z.B. folgende Ziele erreichen: Mönckebergstraße, Hauptbahnhof, Zentralbibliothek, Deichtorhallen, Elbpark Entenwerder, Hamburg Wasser, Industrigebiet Billbrook, S-Allermöhe, Hauni Maschinenbau GmbH, Bahnhof Bergedorf.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	9	\N	\N	City - Hammerbrook - Rothenburgsort - Moorfleet - Allermöhe - Bergedorf	http://www.hamburg.de/radverkehr/426734/veloroute-9/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
20	10	einwärts	\N	Die Veloroute 10 führt von Fischbek- Neugraben über Hausbruch, Heimfeld, Harburg, Wilhelmsburg, Veddel und HafenCity zum Rathausmarkt in der Hamburger Innenstadt. Die 23,5 km werden überwiegend über Nebenstraßen zurück gelegt, ein kleiner Abschnitt verläuft an einer Hauptverkehrsstraße. Dabei können sie z.B. folgende Ziele erreichen: S-Neugraben, Beiersdorf, Daimler, Hamburg Innovation Port, Harburger Binnenhafen, Siedlung Kirchdorf-Süd, Energieberg Georgswerder, Ballinstadt Auswanderermuseum,  Norderelbbrücken, Hafencity, Speicherstadt.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	10	\N	\N	Neugraben - Harburg - Wilhelmsburg - Veddel - HafenCity - City	http://www.hamburg.de/radverkehr/426738/veloroute-10/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
21	10	auswärts	\N	Die Veloroute 10 führt vom Rathausmarkt über die HafenCity, Veddel, Wilhelmsburg, Harburg, Heimfeld und Hausbruch nach Fischbek-Neugraben. Die 23,5 km verlaufen überwiegend über Nebenstraßen, nur ein Abschnitt befindet sich an einer Hauptverkehrsstraße. Dabei können sie z.B. folgende Ziele erreichen: Speicherstadt, HafenCity, Norderelbbrücken, Ballinstadt/Auswanderermuseum, Energieberg Georgswerder, Siedlung Kirchdorf-Süd, Harburger Binnenhafen, Hamburg Innovation Port, Daimler, Beiersdorf, S-Neugraben.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	10	\N	\N	City - HafenCity - Veddel - Wilhelmsburg - Harburg - Neugraben	http://www.hamburg.de/radverkehr/426738/veloroute-10/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
22	11	einwärts	\N	Die Veloroute 11 führt von Eißendorf über Harburg, Wilhelmsburg, Steinwerder und St. Pauli zum Rathausmarkt in der Hamburger Innenstadt. Die 17,6 km verlaufen überwiegend durch nebenstraßen, aber auch durch ein teil der Industrie im Hafen. Dabei können sie z.B. folgende Ziele erreichen: Asklepios Klinik Harburg, Technische Universität Hamburg, S-Harburg Rathaus, Phönix-Center, Wilhelmsburger Inselpark, Behörden für Stadtentwicklung und Wohnen/Energie und Umwelt, Energiebunker, Reiherstieg-Viertel, Blohm&Voss, Alter Elbtunnel, U/S-Landungsbrücken, U-Rödingsmarkt, Handelskammer.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	11	\N	\N	TU Hamburg Harburg - Harburg - Wilhelmsburg - Alter Elbtunnel - City	http://www.hamburg.de/radverkehr/426790/veloroute-11/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
23	11	auswärts	\N	Die Veloroute 11 führt vom Rathausmarkt in der Hamburger Innenstadt über St. Pauli, Steinwerder, Wilhelmsburg und Harburg nach Eißendorf. Die 17,6 km verlaufen überwiegend über Nebnstraßen, aber acuh ein Teil durch die Industrie imHafen. Dabei können sie z.B. folgende ziel erreichen: Handelskammer, U-Rödingsmarkt, U/S-Landungsbrücken, Alter Elbtunnel, Blohm&Voss, Reiherstieg-Viertel, Energiebunker, Behörden für Stadtentwicklung und wohnen/Energie und Umwelt, Wilhelmsburger Inselpark, Phönix-Center, S-Harburg Rathaus, Technische Universität Hamburg, Asklepios Klinik Harburg.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	11	\N	\N	City - Alter Elbtunnel - Wilhelmsburg - Harburg - TU Hamburg Harburg	http://www.hamburg.de/radverkehr/426790/veloroute-11/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
24	12	einwärts	\N	Die Veloroute 12 führt von Altona-Altstadt über St.Pauli zum Rathausmarkt in die Hamburger Innenstadt. Die 5 km verlaufen überwiegend entlang von Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: Bahnhof Altona, IKEA, Fischmarkt, Alter Elbtunnel, U/S-Landungsbrücken, U-Rödingsmarkt, Handelskammer.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	12	\N	\N	Altona - St. Pauli Landungsbrücken - City	http://www.hamburg.de/radverkehr/426798/veloroute-12/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
25	12	auswärts	\N	Die Veloroute 12 führt vom Rathausmarkt in der Hamburger Innenstadt über St.Pauli  in die Altona-Altstadt. Die 5 km verlaufen überwiegend über Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: Handelskammer, U-Rödingsmarkt, U/S-Landungsbrücken, Alter Elbtunnel, Fischmarkt, Königsstraße, Bahnhof Altona.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	12	\N	\N	City - St. Pauli Landungsbrücken - Altona	http://www.hamburg.de/radverkehr/426798/veloroute-12/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
26	13	einwärts	\N	Die Veloroute 13 führt von Hamm über Eilbek, Barmbek-Süd, Winterhude, Eppendorf, Hoheluft, Eimsbüttel nach Altona. Die 13,5 km lange Halbkreisroute führt überwiegend über ein Nebenstraßennetz, aber auch über ein paar Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: U-Burgstraße, Berufliche Schule Burgstraße, U Ritterstraße, Schule für Ernährung und Hauswirtschaft, U-Hamburger Straße, Behörden für Schule und Berufsbildung/Arbeit, Soziales Familie und Integration, Komponistenviertel, Kampnagel, Mühlenkamp, Goldbek-Platz, U-Kellingshusenstraße, Eppendorfer Weg, Neue Flora, S-Holstenstraße, Holstenbrauerei, Bahnhof Altona.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	13	\N	\N	Innere Ringroute: Hamm - Eilbek - Barmbek - Winterhude - Eimsbüttel - Altona	http://www.hamburg.de/radverkehr/426810/veloroute-13/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
27	13	auswärts	\N	Die Veloroute 13 führt von Altona, über Eimsbüttel, Hoheluft, Eppendorf, Winterhude, Barmbek-Süd und Eilbek nach Hamm. Die 13,5 km der Halbkreisförmigen Route führen überwiegend durch und über Nebenstraßen, aber auch in kurzen Abschnitten über Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: Bahnhof Altona, Holstenbrauerei, S-Holstenstraße, Neue Flora, Eppendorfer weg, U-Kellinghusenstraße, Goldbek-Platz, Mühlenkamp, Kampnagel, Komponistenviertel, Behörden für Schule und Berufsbildung/Arbeit, Familie, Soziales und Integration, U-Hamburger Straße, Schule für Ernährung und Hauswirtschaft, U-Ritterstraße, Berufliche Schule Burgstraße, U-Burgstraße.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	13	\N	\N	Innere Ringroute: Altona - Eimsbüttel - Winterhude - Barmbek - Eilbek - Hamm	http://www.hamburg.de/radverkehr/426810/veloroute-13/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
28	14	einwärts	\N	Die Veloroute 14 führt von Billstedt über Jenfeld, Rahlstedt, Farmsen-Berne, sasel, Poppenbüttel, Hummelsbüttel, Langenhorn, Niendorf, Schnelsen, Eidelstedt, Lurup und Bahrenfeld nach Othmarschen. Die 41 km verlaufen überwiegend durch das Nebenstraßenentz, in einigen Teilabsachnitten aber auch entlang von Hauptverkehrsstrßen. Dabei können sie z.B. folgende Ziele erreichen: Billsteder Hauptstraße, Öjendorfer See, Stadtteilzentrum Jenfeld, Berufliche Schule Farmsen, Alster-Einkaufs-Zentrum, Eppendorf AG, Gewerbegebiet Poppenbütteler Weg, U-Langenhorn Markt, Krohnstieg-Tunnel, U-Niendorf-Nord, A-Eidelstedt Zentrum, S-Elbgaustraße, Altonaer Volkspark/Arenen, DESY, Elbe-Einkaufszentrum, S-Othmarschen.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	14	\N	\N	Äußere Ringroute: Billstedt - Poppenbüttel - Niendorf - Schnelsen - Othmarschen	http://www.hamburg.de/radverkehr/426818/veloroute-14/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
29	14	auswärts	\N	Die Veloroute 14 führt von Othmarschen über Bahrenfeld, Lurup, Eidelstedt, Schnelsen, Niendorf, Langenhorn, Hummelsbüttel, Poppenbüttel, Sasel, Farmsen-Berne, Rahlstedt und Jenfeld nach Billstedt. Die 41 km verlaufen überwiegend durch das Nebenstraßennetz, nur in kleinen Teilabschnitten geht es entlang von Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: S-Othmarschen, Elbe-Einkaufszentrum, DESY, Atonaer Volkspark/Arenen, S-Elbgaustraße, A-Eidelstedt Zentrum, U-Niendorf-Nord, Krohnstieg Tunnel, U-Langenhorn Markt, Gewerbegebiet Poppenbüttler Weg, Eppendorf AG, Alster-Einkaufs-Zentrum, Berufliche Schule Farmsen, Stadtteilzentrum Jenfeld, Öjendorfer See, Billstedter Hauptstraße.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	14	\N	\N	Äußere Ringroute: Othmarschen - Schnelsen - Niendorf - Poppenbüttel - Billstedt	http://www.hamburg.de/radverkehr/426818/veloroute-14/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
30	1a	einwärts	\N	Die Veloroute 1a führt von Osdorf über Bahrenfeld, Groß Flottbek, Othmarschen, Ottensen, Altona-Altstadt und St.Pauli zum Rathausmarkt in der Hamburger Innenstadt. Die 13 km lange Route führt überwiegend durch das Nebenstraßennetz in Bahrenfeld für die Route durch einen Grünzug. Dabei können sie z.B. folgende Ziele erreichen: Siedlung Osdorfer Born, Führungsakademie der Bundeswehr, DESY, Asklepios Klinik Altona, UCI-Entertainment-Center Othmarschen, Bahnhof Altona, Heiligengeistfeld, Messehallen, Laeiszhalle.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	1a	\N	\N	Osdorfer Born - Groß Flottbek - Othmarschen - Altona - City	http://www.hamburg.de/radverkehr/418898/veloroute-1/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
31	1a	auswärts	\N	Die Veloroute 1a führt vom Rathausmarkt in der Hamburger Innenstadt über St.Pauli, Altona-Altstadt, Ottensen, Othmarschen, Groß Flottbek und Bahrenfeld nach Osdorf. Die 13 km lange Route führt überwiegend durch das Nebenstraßennetz, in einem kurzen Abschnitt geht es in Bahrenfeld durch einen Grünzug. Dabei können sie z.B. folgende Ziele erreichen: Laeizhalle, Messehallen, Heiligengeistfeld, Bahnhof Altona, UCI-Entertainment-Center Othmarschen, Asklepios Klinik Altona, DESY, Führungsakademie der Bundeswehr, Siedlung Osdorfer Born.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	1a	\N	\N	City - Altona - Othmarschen - Groß Flottbek - Osdorfer Born	http://www.hamburg.de/radverkehr/418898/veloroute-1/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
32	5a	einwärts	\N	Die Veloroute 5a führt von Alsterdorf über Winterhude, Barmbek-Süd, Uhlenhorst, Hohenfelde und St.Georg zum Rathausmarkt in der Hamburger Innenstadt. Die 9 km führen überwiegend entlang von Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: Flughafen, City Nord, Stadtpark, U-Hamburger Straße, Behörden für Schule und Berufsbildung/Arbeit, Soziales, Familie und Integration,  östliches Alsterufer, Kunsthalle.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	5a	\N	\N	Alsterdorf - Barmbek-Süd - Uhlenhorst - City	http://www.hamburg.de/radverkehr/426674/veloroute-5/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
33	5a	auswärts	\N	Die Veloroute 5a führt vom Rathausmarkt in der Hamburger Innenstadt über St. Georg, Hohenfelde, Uhlenhorst, Barmbek-Süd und Winterhude nach Alsterdorf. Die 9 km verlaufen überwiegend entlang von Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: Kunsthalle, östliches Alsterufer, Behörden für Schule und Berufsbildung/Arbeit, Soziales, Familie und Integration, U-Hamburger Straße, Stadtpark, City Nord, Flughafen.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	5a	\N	\N	City - Uhlenhorst - Barmbek-Süd - Alsterdorf	http://www.hamburg.de/radverkehr/426674/veloroute-5/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
34	7a	einwärts	\N	Die Veloroute 7a führt von Jenfeld über Marienthal, Eilbek, Hohenfelde und St. Georg zum Rathausmarkt in der Hamburger Innenstadt. Die 12 km verlaufen überwiegend über Nebenstraßen. Dabei können sie z.B. folgende Ziele erreichen: Stadtteilzentrum Jenfeld, Asklepios Klinik Wandsbek, Bahnhof Wandsbek, U-Wandsbek Markt, Marienkrankenhaus, Gewerbeschulen Angerstraße, Hochschule für Angewandte Wissenschaften, Asklepios Klinik St. Georg, Museum für Kunst und Gewerbe, Hauptbahnhof, Mönckebergstraße. 	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	7a	\N	\N	Jenfeld - Wandsbek-Markt - Eilbek - St.Georg - City	http://www.hamburg.de/radverkehr/426718/veloroute-7/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
35	7a	auswärts	\N	Die Veloroute 7a führt vom Rathausmarkt in der Hamburger Innenstadt über St. Georg, Hohenfelde, Eilbek und Marienthal nach Jenfeld. Die 12 km verlaufen überwiegend über Nebenstraßen. Dabei können sie z.B. folgende Ziele erreichen: Mönckebergstraße, Hauptbahnhof, Museum für Kunst und Gewerbe, Asklepios Klinik St. Georg, Hochschule für Angewandte Wissenschaften, Gewerbeschulen angerstraße, Marienkrankenhaus, U-Wandsbek Markt, Bahnhof Wandsbek, Asklepios Klinik Wandsbek, Stadtteilzentrum Jenfeld.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	7a	\N	\N	City - St. Georg - Eilbek - Wandsbek-Markt - Jenfeld 	http://www.hamburg.de/radverkehr/426718/veloroute-7/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
36	8a	einwärts	\N	Die Veloroute 8a führt von Mümmelmannsberg über Billstedt, Horn, Hamm, Borgfelde und St.Georg zum Rathausmarkt in der Hamburger Innenstadt. Die 12 km verlaufen überwiegend entlang von Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: U-Mümmelmannsberg, Billstedter Hauptstraße, Horner Rennbahn, Berufs- und Gewerbeschulen Hammer Landstraße, U/S-Berliner Tor, Hochschule für Angewandte Wissenschaften, Agentur für Arbeit, Museum für Kunst und Gewerbe, Hauptbahnhof, Mönckebergstraße.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	8a	\N	\N	Mümmelmannsberg - Kirch-Steinbek - Billstedt - Hamm - Borgfeld - City	http://www.hamburg.de/radverkehr/426726/veloroute-8/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
37	8a	auswärts	\N	Die Veloroute 8a führt vom Rathausmarkt in der Hamburger Innenstadt über St.Georg, Borgfelde, Hamm, Horn und Billstedt nach Mümmelmannsberg. Die 12 km verlaufen überwiegend  entlang von Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: Mönckebergstraße, Hauptbahnhof, Museum für Kunst und Gewerbe, Agentur für Arbeit, Hochschule für Angewandte Wissenschaften, U/S-Berliner Tor, Berufs- und Gewerbeschulen Hammer Landstraße, Horner Rennbahn, Billstedter Hauptstraße, U-Mümmelmannsberg.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	8a	\N	\N	City - Borgfelde - Hamm - Billstedt - Kirch-Steinbek - Mümmelmannsberg	http://www.hamburg.de/radverkehr/426726/veloroute-8/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
38	11a	einwärts	\N	Die Veloroute 11a verbindet die Veloroute 11 aus Eißendorf im norden Wilhelmsburg mit der Veloroute 10, die in die Innenstadt weiterführt. Die 11,5 km verlaufen von Eißendorf über Harburg und Wilhelmsburg nach Veddel überwiegend getrennt vom Kfz-Verkehr, im Kerngebiet von Harburg auf schnellstem Weg über Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: Asklepios Klinik Harburg, TU Hamburg, S-Harburg Rathaus, Phönix-Center, Wilhelmsburger Inselpark, Behörden für Stadtentwicklung und Wohnen/Energie und Umwelt, Ballinstadt/Auswanderermuseum, S-Veddel.	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	11a	\N	\N	Eißendorf-Harburg-Wilhelmsburg-Veddel	http://www.hamburg.de/radverkehr/426790/veloroute-11/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
39	11a	auswärts	\N	Die Veloroute 11a zweigt auf der Veddel von der Veloroute 10 ab und mündet in Wilhelmsburg in die Veloroute 11 Richtung Harburg und Eißendorf. Die 11,5 km verlaufen überwiegend getrennt vom Kfz-Verkehr, im Harburger Kerngebiet auf dem kürzesten Weg auf Hauptverkehrsstraßen. Dabei können sie z.B. folgende Ziele erreichen: S-Veddel, Ballinstadt/Auswanderermuseum, Behörden für Stadtentwicklung und wohnen/Energie und Umwelt, Wilhelmsburger Inselpark, Phönix-Center, S-Harburg Rathaus, TU Hamburg, Asklepios Klinik Harburg	Digitalisiert durch die Behörde für Wirtschaft, Verkehr und Innovation Hamburg	11a	\N	\N	Veddel-Wilhelmsburg-Harburg-Eißendorf	http://www.hamburg.de/radverkehr/426790/veloroute-11/	Routenbeschreibung im Internet	\N	\N	\N	\N	\N	\N	\N	\N
\.


--
-- TOC entry 5611 (class 0 OID 0)
-- Dependencies: 626
-- Name: metadaten_id_seq; Type: SEQUENCE SET; Schema: radverkehr; Owner: postgres
--

SELECT pg_catalog.setval('radverkehr.metadaten_id_seq', 39, true);


--
-- TOC entry 5467 (class 2606 OID 210730)
-- Name: metadaten metadaten_pkey; Type: CONSTRAINT; Schema: radverkehr; Owner: postgres
--

ALTER TABLE ONLY radverkehr.metadaten
    ADD CONSTRAINT metadaten_pkey PRIMARY KEY (id);


-- Completed on 2019-05-24 08:48:22

--
-- PostgreSQL database dump complete
--

